### PR TITLE
Clarify Colcon and vcs are build dependencies

### PR DESCRIPTION
**Pull request by ted-miller**
There was a user missing vcs and colcon. I want to emphasize the prereqs in this procedure.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
> There was a user missing vcs and **colcon**

how would you build ROS packages without Colcon?

It's already installed with the default ROS 2 install:

> Development tools: Compilers and other tools to build ROS packages
> 
> ```
> sudo apt install ros-dev-tools
> ```

**Comment by gavanderhoorn** [comment]
I just don't like duplicating content 'everywhere'.

This also links to the Humble installation documentation which will become obsolete at some point and won't work for users looking to install ROS on newer Ubuntu versions (fi).

**Comment by gavanderhoorn** [comment]
@ted-miller: I've updated the PR.

Let me know what you think.

I still don't like repeating this sort of information 'everywhere', but if it's necessary, it's necessary.

**Comment by ted-miller** [comment]
Personally, I think the distribution of instructions for the individual components can be confusing. So providing guidance to the proper procedures is helpful. 

I think your update is good.

**Review by gavanderhoorn — APPROVED** [review]

**Pull request merged**
